# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
permalink: /:title

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		      "Minimal Uni, A Pleasant Jekyll Theme"
description:	      "This is the base jekyll website template for my university courses, also convenient for a blog or wiki."
author:              "Lee Tusman"


baseurl: "/minimal-university" # the subpath of your site, e.g. /blog
url: "https://leetusman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 2sman2sman
github_username:  lee2sman
